
source ./build-wasm-config.sh

em++ -O2 $COMBINED_SETTINGS \
-MINIMAL_RUNTIME=1 \
-sWARN_UNALIGNED=1 -sNO_DISABLE_EXCEPTION_CATCHING -sNO_EXIT_RUNTIME \
-sSTACK_OVERFLOW_CHECK=2 -sEXCEPTION_DEBUG=1 \
-Wcast-align -Wover-aligned \
$FILE_INPUT $FILE_OUTPUT
